project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "Учебн🤖к"
  description: "Учебник по искусственному интеллекту — углублённый уровень, 10–11 классы"
  navbar:
    left:
      - text: "🏠 Главная"
        href: index.html
      - text: "📐 Дополнительный учебник"
        href: dop/
      - text: "📘 10 класс"
        href: 10/
      - text: "📗 11 класс"
        href: 11/

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    html-math-method: katex
    toc: false
    page-layout: full
