#!/usr/bin/env bash
# Собирает нативный фреймворк живых виджетов:
#   scripts/interactive/core.js + scripts/interactive/widgets/*.js
#     → docs/assistant/interactive.js   (один бандл, инъектится nginx-ом)
#   scripts/interactive/interactive.css → docs/assistant/interactive.css
#
# Порядок: core.js всегда первым (определяет SigmaInt.register), затем виджеты
# по алфавиту. Идемпотентно. Запускать после правок любого виджета.
set -euo pipefail
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/interactive" && pwd)"
OUT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../docs/assistant" && pwd)"

BUNDLE="${OUT}/interactive.js"
{
  echo "// AUTO-GENERATED by scripts/build_interactive.sh — НЕ редактировать здесь."
  echo "// Источники: scripts/interactive/core.js + scripts/interactive/widgets/*.js"
  echo ""
  cat "${SRC}/core.js"
  echo ""
  for f in "${SRC}/widgets/"*.js; do
    [ -e "$f" ] || continue
    echo ""
    echo "// ===== widget: $(basename "$f") ====="
    cat "$f"
    echo ""
  done
} > "${BUNDLE}"

cp "${SRC}/interactive.css" "${OUT}/interactive.css"

WIDGETS=$(ls "${SRC}/widgets/"*.js 2>/dev/null | wc -l)
echo "✓ interactive.js собран: core + ${WIDGETS} виджет(ов) → ${BUNDLE}"
echo "✓ interactive.css → ${OUT}/interactive.css"
